# Generated by Django 3.0.8 on 2021-11-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('cantidad_imagenes', models.IntegerField(default=0)),
                ('id_categoria', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='anuncios.Categoria')),
                ('id_subcategoria', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='anuncios.Subcategoria')),
            ],
        ),
    ]
