# Generated by Django 3.0.8 on 2021-11-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_imagen_pagos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagos',
        ),
    ]
