# Generated by Django 3.0.8 on 2021-11-23 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_delete_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, null=True)),
                ('medio_pago', models.CharField(max_length=100, null=True)),
                ('numero_referencia', models.IntegerField(null=True)),
                ('id_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.Anuncio')),
            ],
        ),
    ]
