# Generated by Django 3.0.8 on 2021-11-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_pagos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='cantidad_imagenes',
        ),
    ]
