# Generated by Django 3.0.8 on 2021-11-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0009_auto_20211123_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='alt_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
