# Generated by Django 3.0.8 on 2021-11-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0011_assets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='nombre',
            new_name='ubicacion',
        ),
    ]
